name: lens4d
version: 0.0.0
description: Basic functional lens library. Build composable, reusable type-safe lenses.
repository: https://github.com/onehundredandeighty/lens4d
environment:
  sdk: ^3.7.0
topics:
  - lens
  - lenses
  - functional-programming

dev_dependencies:
  test: ^1.16.0
